### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by ciaoben** [OutwalkStudios/exalt#1]
Hi, first of all, congrats for this new project, it seems REALLY REALLY well done!

I was wondering if Server Side Rendering is something that it is supported or plan to be.

**Comment by jleeson** [comment]
Thank you! Server side rendering is not currently supported but we do have both server side rendering and static site generation planned before reaching v1.

server side rendering has been planned from the start for exalt so it wont be much longer before its implemented.

**Comment by ciaoben** [comment]
This is a great news. Thanks for the clarification.

**Comment by teamflp** [comment]
Bonjour, bravo pour ce travail génial !
S'il vous plaît, y aurait-il un moyen plus adapté pour créer un composant ?

Depuis tout à l'heure après avoir installé exalt j'essai de créer un composant mais je n'arrive pas. 
Franchement ce Framework est séduisant.

**Comment by jleeson** [comment]
Bonjour @teamflp , merci pour les gentils mots. Cette question concerne le soutien à la RSS. Je vais ouvrir un nouveau numéro et répondre à votre question là-bas.

**Comment by jleeson** [comment]
Update for progress on SSR support. In the next release v0.6 the framework runtime will be able to self hydrate components as they load. So we will be able to move forward with getting the node rendering portion of the framework implemented.

**Comment by jleeson** [comment]
SSR/SSG is in the final stages of testing before we integrate it into @exalt/toolchain. Getting pretty close to this feature being ready and releasing v1.

<img width="841" alt="Screen Shot 2021-09-11 at 2 01 47 PM" src="https://user-images.githubusercontent.com/48230879/132961910-6ae324ae-72a0-416f-86fd-47819140c738.png">

**Comment by jleeson** [comment]
@exalt/ssr is now public and released on npm. You can now use it to render your components on the server and either use them as SSR or SSG. We will be working on improving it further and integrating it with @exalt/toolchain for automatic prerendering soon.

https://github.com/exalt/exalt-ssr

**Comment by jleeson** [comment]
@exalt/toolchain now provides a `prerender` option that will compile your app to static html files, the exalt runtime will then hydrate the components as the load making them interactive. to start simply create an exalt app and run

```
exalt build --prerender
```

and you will have static files you can deploy.

Given @exalt/ssr can be used for SSR and @exalt/toolchain provides SSG, this will make the issue as closed. 🎊
