### ISSUE TITLE
Strange behaviour with css custom properties

### ISSUE THREAD

**Issue by ciaoben** [OutwalkStudios/exalt#2]
I am trying to control the style of a component using custom properties (the platform way of customizing styles for custom elements).

In my component I have:
```
:host {
  --color-fallback: yellow;
}

button {
  background-color: var(--color, var(--color-fallback));
}
``` 

and in an external stylesheet I am setting the custom property `--color`:

```
	<style>
		my-counter {
			--color: red;
		}
	</style>
```

I would expect the property `--color` to work in my component, but it doesn't. Am I missing something?

Here is a link with the problem reproduced:

https://webcomponents.dev/edit/Jz2waxeiY2pgKFsojP37/src/index.js

**Comment by jleeson** [comment]
Hey @ciaoben, thanks for making this issue. I could not get the css variable to work properly on webcomponents.dev just as your example shows but when using a project generated using the exalt cli. it had no problem changing the color to red.

Did you run into this while developing with the cli and toolchain or was it only present on webcomponents.dev?

**Comment by ciaoben** [comment]
Yes I pinned down the problem. It is not a problem with exalt, it is a problem of ShadowDOM nesting.
Basically I am trying to set the custom property on the root level but was expecting to arrive to a double nested custom element. 

It seems browser does not support this.

Sorry for the false alarm

**Comment by jleeson** [comment]
No worries. it looks like you have things working now in your example. On another note, im not sure if webcomponents.dev has exalt 0.3 or 0.2 atm but if its 0.3 and you dont want to keep referencing `state` you can use the reactive function.

```js
count = super.reactive(0);
value = super.reactive("");
```

**Comment by ciaoben** [comment]
@jleeson great to hear that! Thanks, I was trying playing around with `super.reactive` but it seems to have some problems (or gotchas that I don't get :) ).

`state` and `super.reactive` does not seem to behave the same way, here a reproduction:

https://webcomponents.dev/edit/W6uRz4jPjqwrUfmLv3Lt/src/index.js

If a use state, all works as expected. When using `super.reactive` with an array, in the first render it does not receive and array but another object.

Is it normal?

**Comment by jleeson** [comment]
Hey @ciaoben I took a look and while a reactive property does start as a plain object before rendering, the value is wrapped in a Proxy to make it reactive. This does appear to be a bug as its happening in all cases when using an array. it seems that array methods are not working on it at all.

I will get a fix out for this when I wake up, in the mean time i will just open this as its own issue.
