### ISSUE TITLE
bug: reactive array not working properly.

### ISSUE THREAD

**Issue by jleeson** [OutwalkStudios/exalt#3]
When using a reactive property with the value of an array, array methods such as `map` no longer work. The intended behavior is for the array to be wrapped in a Proxy and maintain the original array methods.

Reproduction provided by ciaoben: https://webcomponents.dev/edit/W6uRz4jPjqwrUfmLv3Lt/src/index.js

**Comment by ciaoben** [comment]
It seems to me that is not exactly that array methods are not working, but that the object that the first render sees is not the proxied array at all:

![immagine](https://user-images.githubusercontent.com/4526061/118100425-b8d0d880-b3d6-11eb-902d-bfdb82e09d52.png)

It seems to be a custom object with `_reactive` prop and value containing the array

**Comment by jleeson** [comment]
Yes, you are correct. When I was reading the stack trace however it looked like it was throwing from inside a proxy but your right it’s not being transformed into the actual reactive property.
